name: Rollback

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Tag da versão para rollback (ex: v1.0.0)'
        required: true

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Voltar para versão especificada
        run: |
          git fetch --tags
          git checkout ${{ github.event.inputs.version }}
          git push origin main --force
